#!/bin/sh
#install PiHPSDR(2.0-rc15) with wdsp(1.18)
#N4XWE 12-8-2020
#Visit http://www.iquadlabs.com


#Update the apt cache and upgrade the system packages to their latest versions
sudo apt update && sudo apt upgrade -y

#Add all of the dependencies
sudo apt -y install git libfftw3-dev libgtk-3-dev libasound2-dev libusb-1.0-0-dev wiringpi libsoapysdr-dev ||
	{ echo 'Dependency installation failed'; exit 1; }

#Add and enable a 2GB Swapfile
sudo fallocate -l 2G /swapfile
sudo chmod 600 /swapfile
sudo mkswap /swapfile
sudo swapon /swapfile

#Create a unique directory for the PIHPSDR compile and make it the current directory
mkdir -p ~/src/PIHPSDR && cd ~/src/PIHPSDR

#Clone the most recent version of the wdsp source code from github
git clone https://github.com/g0orx/wdsp ||
  { echo 'Unable to download the wdsp source code file'; exit 1; }
 
#Make the directory containing the wdsp source code the current directory
cd ~/src/PIHPSDR/wdsp

#Compile and install the wdsp libraries
make && sudo make install ||
  { echo 'Unable to install the wdsp Libraries'; exit 1; }

#Make the unique directory previously created for the compile the current directory 
cd ~/src/PIHPSDR

#Clone the most recent version of the pihpsdr source code from github
git clone https://github.com/g0orx/pihpsdr

#Make the directory containing the pihpsdr source code the current directory
cd ~/src/PIHPSDR/pihpsdr

#Compile and install the pihpsdr souce code
make && make release

#Copy the Release tarball generated by "make release" to the $HOME directory
cp ~/src/PIHPSDR/pihpsdr/release/pihpsdr.tar ~

#Make the $HOME directory the current directory
cd ~

#Extract the pihpsdr Release files from the pihpsdr tarball
tar xvf pihpsdr.tar

#Make the directory containing the pihpsdr release tarball the current directory
cd ~/pihpsdr

#Run the pihpsdr install script
./install.sh

#If the Start button appears in the Dscovery window, left click on it to start pihpsdr.  If the Subnet! 
#notification appears, right click on the Network icon in the upper right corner of the desktop.  From 
#the menu that appears select "Wireless & Wired Network Settings" From the Network Preferences menu select
#Configure: interface eth0, check the box labled "Disable IPv6" in the IPv4 box insert an IP address
#that is on the Subnet of the IP address of the IQ2 (For example 192.168.1.10 for an IQ2 configured with
#the standard 192.168.1.25, no DHCP setting). Restart pihpsdr. The Start button should appear the next time the
#piHPSDR Discovery menu appears.

#When pihpsdr starts for the first time it generates wisdom file which takes a few minutes, and a configuration file named [The MAC address of the RPi].props

#Shut down piHPSDR and edit the [The MAC address of the RPi].props file to:
#change receivers=2 to receivers=1
#change receiver.1.sample_rate=48000 to =384000

#Start pihpsdr.


